name: observable_zombies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flame: ^1.18.0
  flame_tiled: ^1.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/world.tmx
    - assets/town/
    - assets/dungeon/
    - assets/characters/Adventurer/
    - assets/characters/Adventurer/Poses/
    - assets/characters/Zombie/
    - assets/characters/Soldier/
    - assets/characters/Female/
    - assets/characters/Player/
